### PR TITLE
Add talking points for Zuul Interoperability

### PR DESCRIPTION
**Pull request by fungi**
This is the source for the slide deck which accompanied my Zuul
Interoperability talk during the 2020-03-019 CD Foundation
Interoperability SIG meeting. It can be used with pandoc to generate
reveal.js or PDF slide decks as follows:

    pandoc -t revealjs -s -o zuul-interop_2020-03-019.html \
        zuul-interop_2020-03-019.rst -V revealjs-url=./r

    pandoc -t beamer -o zuul-interop_2020-03-019.pdf \
        zuul-interop_2020-03-019.rst

### CODE REVIEW

**Comment by fungi** [comment]
I licensed the file CC-BY, which should be entirely compatible with Apache License Version 2.0, but I'm happy to make adjustments to grant redistribution under a different license if needed.

**Comment by fdegir** [comment]
can we get this PR accepted so we can link this in presentation schedule document?

**Comment by tracymiranda** [comment]
Typically we have added in pdf files that are readily consumable and match what is shown in the videos. Maybe it might be better to store the generated pdf here (we can always link to source in a zuul repo)?

**Comment by fungi** [comment]
ReStructuredText is meant to be readily consumable on its own, but the deck was designed to be presented by a slide tool like PresenTTY which takes RST as an input format.

My guess is it was displayed with a Web browser showing the RevealJS build at http://fungi.yuggoth.org/presentations/2020-cdf/slides.html (I don't actually know for sure, as I was dialed in by phone to present), but since other decks in here were only single files I didn't want to push up the file tree for the HTML/JS bits (the RevealJS files are MIT licensed so should also be compatible with the overall licensing of this repository, if that's a preferable format).

I provided a convenience PDF export using LaTeX Beamer, but it's fairly rough: http://fungi.yuggoth.org/presentations/2020-cdf/zuul-interop-slides.pdf

Both the RevealJS and PDF versions linked here were built with the popular Pandoc document converter utility, nothing complicated.

**Pull request merged**
